In [1]:
import numpy as np

# Solicitation
sig_tilde = 1e6

# Material parameters
K = 1e9
b = 0.5
N = 1e9

K = np.array([[K, -b], [b, 1 / N]])
F = np.array([-sig_tilde, 0])

In [2]:
# Calculating the inverse of K
K_inv = np.linalg.inv(K)
# Getting U
U = np.dot(K_inv, F)
print("The corresponding state is : epsilon = {:.4f}, p = {} Pa.".format(*U))

The corresponding state is : epsilon = -0.0008, p = 400000.0 Pa.


In [3]:
# Checking that KU=F
print("Result of K*U: sigma = {} Pa, phi - phi0 = {}.".format(*np.dot(K, U)))

Result of K*U: sigma = -1000000.0000000001 Pa, phi - phi0 = -4.8466166450707e-20.


In [4]:
def gauss_elimination(A):
    # Here M is an "augmented" matrix, what matters is the number of rows
    M = (
        A.copy()
    )  # Creating a copy of the original matrix, otherwise it will be modified by the function
    nb_rows = M.shape[0]
    for i in range(nb_rows):
        # Check if our pivot is 0
        if M[i, i] == 0:  # We need to swap rows
            j = i
            while M[j, i] == 0:
                if j >= nb_rows:
                    return None
                else:
                    j += 1
            # Swap rows i and j
            aux_row = M[i, :].copy()
            M[i, :] = M[j, :].copy()
            M[j, :] = aux_row
            print("Swapped rows {} and {}:".format(i, j))
            print(M)
        # Now our pivot is non-zero
        M[i, :] = M[i, :] / M[i, i]
        print("Reduced pivot in row {} to 1:".format(i))
        print(M)
        for k in range(nb_rows):
            if k != i:
                M[k, :] = M[k, :] - M[i, :] * M[k, i]
        print("Eliminated other values in column {}:".format(i))
        print(M)
    return M


# Defining our matrices
K = np.array([[2, 1, -1], [4, 2, 2], [-2, 1, 2]], dtype=float)
F = np.array([8, -11, 3], dtype=float).reshape(3, 1)
A = np.hstack((K, F))

# Checking the algorithm against matrix inversion
M = gauss_elimination(A)
print("Solution from Gauss elimination: X={}".format(M[:, -1]))
sol = np.dot(np.linalg.inv(K), F).reshape(
    3,
)
print("Actual solution: X={}".format(sol))
print("You succeeded!" if np.all(M[:, -1] == sol) else "Check your algorithm!")

Reduced pivot in row 0 to 1:
[[  1.    0.5  -0.5   4. ]
 [  4.    2.    2.  -11. ]
 [ -2.    1.    2.    3. ]]
Eliminated other values in column 0:
[[  1.    0.5  -0.5   4. ]
 [  0.    0.    4.  -27. ]
 [  0.    2.    1.   11. ]]
Swapped rows 1 and 2:
[[  1.    0.5  -0.5   4. ]
 [  0.    2.    1.   11. ]
 [  0.    0.    4.  -27. ]]
Reduced pivot in row 1 to 1:
[[  1.    0.5  -0.5   4. ]
 [  0.    1.    0.5   5.5]
 [  0.    0.    4.  -27. ]]
Eliminated other values in column 1:
[[  1.     0.    -0.75   1.25]
 [  0.     1.     0.5    5.5 ]
 [  0.     0.     4.   -27.  ]]
Reduced pivot in row 2 to 1:
[[ 1.    0.   -0.75  1.25]
 [ 0.    1.    0.5   5.5 ]
 [ 0.    0.    1.   -6.75]]
Eliminated other values in column 2:
[[ 1.      0.      0.     -3.8125]
 [ 0.      1.      0.      8.875 ]
 [ 0.      0.      1.     -6.75  ]]
Solution from Gauss elimination: X=[-3.8125  8.875  -6.75  ]
Actual solution: X=[-3.8125  8.875  -6.75  ]
You succeeded!


In [5]:
M = np.array(
    [
        [4, 0, 2, 2, 3],
        [9, 3, 2, 0, 2],
        [0, 9, 1, 9, 7],
        [1, 1, 9, 4, 8],
        [7, 8, 9, 3, 3],
    ],
    dtype=float,
)

# Make Identity Matrix
I = np.zeros((5, 5))
for i in range(5):
    I[i, i] = 1

M_inv = gauss_elimination(np.hstack((M, I)))[:, 5:]
print("Checking M^-1.M: {}".format(np.dot(M_inv, M)))

Reduced pivot in row 0 to 1:
[[1.   0.   0.5  0.5  0.75 0.25 0.   0.   0.   0.  ]
 [9.   3.   2.   0.   2.   0.   1.   0.   0.   0.  ]
 [0.   9.   1.   9.   7.   0.   0.   1.   0.   0.  ]
 [1.   1.   9.   4.   8.   0.   0.   0.   1.   0.  ]
 [7.   8.   9.   3.   3.   0.   0.   0.   0.   1.  ]]
Eliminated other values in column 0:
[[ 1.    0.    0.5   0.5   0.75  0.25  0.    0.    0.    0.  ]
 [ 0.    3.   -2.5  -4.5  -4.75 -2.25  1.    0.    0.    0.  ]
 [ 0.    9.    1.    9.    7.    0.    0.    1.    0.    0.  ]
 [ 0.    1.    8.5   3.5   7.25 -0.25  0.    0.    1.    0.  ]
 [ 0.    8.    5.5  -0.5  -2.25 -1.75  0.    0.    0.    1.  ]]
Reduced pivot in row 1 to 1:
[[ 1.          0.          0.5         0.5         0.75        0.25
   0.          0.          0.          0.        ]
 [ 0.          1.         -0.83333333 -1.5        -1.58333333 -0.75
   0.33333333  0.          0.          0.        ]
 [ 0.          9.          1.          9.          7.          0.
   0.          1.  